version: "3"

services:
  db:
    container_name: srtd-media-batch-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
      MYSQL_DATABASE: db
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  app:
    depends_on:
      - db
    container_name: "srtd-media-batch-app"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
      MYSQL_DATABASE: db
    volumes:
      - ./app:/usr/src/app
    tty: true
