# fly.toml app configuration file generated for srtd-media-batch on 2024-01-12T12:42:32+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "srtd-media-batch"
primary_region = "nrt"

[build]

[processes]
  # web = "gunicorn app.app:app"
  cron = "supercronic /usr/src/app/crontab"

#[http_service]
#  internal_port = 8080
#  force_https = true
#  auto_stop_machines = true
#  auto_start_machines = true
#  min_machines_running = 0
#  # processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
